<?php
/**
 * Makewebbetter
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement(EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://makewebbetter.com/license-agreement.txt
 *
 * @category    Makewebbetter
 * @package     Makewebbetter_HubIntegration
 * @author      Makewebbetter Core Team <connect@makewebbetter.com>
 * @copyright   Copyright Makewebbetter(http://makewebbetter.com/)
 * @license     https://makewebbetter.com/license-agreement.txt
 */

/* @var $block \Makewebbetter\HubIntegration\Block\Adminhtml\System\Config\AuthorizeButton */
?>

<script type="text/x-magento-init">
        {
        "*" :{
        "Makewebbetter_HubIntegration/js/authorize":{
           "AuthorizeUrl" : "<?= /* @noEscape */ $block->getAjaxSyncUrl(); ?>"
                 }
             }
        }

    </script>

<?= /* @noEscape */ $block->getButtonHtml() ?>
<?php if($block->getConnectionStatus()){ ?>
<p>Hubspot Portal Id: <span class='hub_portal_id'><?= /* @noEscape */ $block->getHubspotPortalId() ?></span> <p>
<?php }?>
