<?php
/** @var  $block \Makewebbetter\HubIntegration\Block\Authorize\Mapping */
$formAction = $block->baseUrl().'hubintegration/config/mappingsaved';
$status = $block->getConnectionStatus();
$pipelines = [];
$hubPipelineDetails = [];
$pipelinesWithStages = [];
$userStageData = [];
$defaultStage = [];
$magentoOrderStatus = [];
$defaultStageCheck = [];
$defaultStageCheck = json_decode($block->connectionManager->getHubConfig( 'hub_ecomm_default_mapping'), true);;
$showPipeline = '';
if($status) {
    $block->setHubPipelineAndStageDetails();
    $dealPipelinesresponse = $block->getHubPipelineDetails();

    if(!empty($dealPipelinesresponse) && isset($dealPipelinesresponse['results'])){
        $hubPipelineDetails = $dealPipelinesresponse['results'];
    }

    $pipelines = json_decode($block->connectionManager->getHubConfig('hub_all_pipeline_id'), true);
    $allpipelineDetails = json_decode($block->connectionManager->getHubConfig('hub_all_pipeline_detail'), true);

    $allpipelineDetails = json_decode($block->connectionManager->getHubConfig('hub_all_pipeline_detail'), true);
    $userData = json_decode($block->connectionManager->getHubConfig( 'hub_user_raw_deal_stage_mapped'), true);

    $userPipeline = $block->connectionManager->getHubConfig( 'hub_user_selected_pipeline');

    $defaultStageCheck = json_decode($block->connectionManager->getHubConfig( 'hub_ecomm_default_mapping'), true);;

    if(!empty($userPipeline)){
        $showPipeline = $userPipeline;
    }else{
        $showPipeline = 'Ecommerce Pipeline';
    }
    if(!empty($userData)) {
        foreach ($userData as $key => $value) {
            if ($key == $showPipeline)
                foreach ($value as $skey => $svalue) {
                    $userStageData[$svalue['magento_order_status_code']] = $svalue['hubspot_deal_stage_id'];
                }
        }
    }
    foreach ($allpipelineDetails as $pkey => $pipeline) {
        if ($pkey == $showPipeline) {
            foreach ($pipeline as $skey => $stage) {
                $defaultStage[$skey] = $stage;
            }
        }
    }
    foreach($hubPipelineDetails as $pipeline){
        $pipelines[$pipeline['id']] = $pipeline['label'];
        foreach($pipeline['stages'] as $key => $stage){
            $pipelinesWithStages[$pipeline['label']][$stage['id']] = $stage['label'];
        }
    }
    $magentoOrderStatus =  $block->connectionManager->getmagentoOrderStatus();
}


?>
<div>
    <div class="pipeline-stage-mapping">
        <h2 class="title">Pipeline and Deal Stages Mapping</h2>
        <form action ="<?= /* @noEscape */ $formAction ?>" method="post" id="mapping_form">
            <table>
                <tbody>
                <tr>
                    <td>
                        <label for="pipeline"><h3>Select Pipeline </h3></label>
                    </td>
                    <td>
                        <select name="selected_pipeline" id="selected_pipeline">
                            <?php foreach($pipelines as $id => $pipeline){
                                if($pipeline == $showPipeline){
                                ?>
                                    <option selected="<?= /* @noEscape */ $pipeline ?>" name="<?= /* @noEscape */ $id ?>" value="<?= /* @noEscape */ $pipeline ?>"><?= /* @noEscape */ $pipeline ?></option>
                                <?php
                                }else{
                                ?>
                                    <option name="<?= /* @noEscape */ $id ?>" value="<?= /* @noEscape */ $pipeline ?>"><?= /* @noEscape */ $pipeline ?></option>
                                <?php } } ?>
                        </select>
                    </td>
                </tr>
                </tbody>
            </table>
            <hr>
            <h2 class="title">Deal Stages Mapping </h2>
           <div id="change_pipeline_stage">
               <table>
                   <tbody>
                       <tr>
                           <th>
                               <label ><h3>Magento Order Status </h3></label>
                           </th>
                           <th>
                               <label ><h3>HubSpot Deal Status </h3></label>
                           </th>
                       </tr>
                   <?php
                   if(!empty($userStageData)){
                       foreach($magentoOrderStatus as $code => $mlabel){ ?>
                           <tr>
                               <td>
                                   <label ><?= /* @noEscape */ $mlabel ?> </label>
                               </td>
                               <td>
                                   <select name="<?= /* @noEscape */ $code ?>" id="selected_pipeline_stage">
                                       <?php foreach($defaultStage as $id => $hlabel){
                                           $selected = false;
                                           foreach($userStageData as $uStatusCode => $uDealId) {
                                               if ($code == $uStatusCode && $id == $uDealId) {
                                                   ?>
                                                   <option selected="<?= /* @noEscape */ $hlabel ?>" name="<?= /* @noEscape */ $id ?>" value="<?= /* @noEscape */ $id ?>"><?= /* @noEscape */ $hlabel ?></option>
                                                   <?php
                                                   $selected = true;
                                               }
                                           }
                                       if($selected == false){
                                           ?>
                                           <option name="<?= /* @noEscape */ $id ?>" value="<?= /* @noEscape */ $id ?>"><?= /* @noEscape */ $hlabel ?></option>
                                       <?php } } ?>
                                   </select>
                               </td>
                           </tr>
                       <?php }
                   }
                   else{
                   foreach($magentoOrderStatus as $code => $mlabel){ ?>
                       <tr>
                           <td>
                               <label ><?= /* @noEscape */ $mlabel ?> </label>
                           </td>
                           <td>
                               <select name="<?= /* @noEscape */ $code ?>" id="selected_pipeline_stage">
                                   <?php foreach($defaultStage as $id => $hlabel){
                                       $selected = false;
                                       foreach($defaultStageCheck as $uStatusCode => $uDealId) {
                                           if ($code == $uStatusCode && $id == $uDealId) {
                                               ?>
                                               <option selected="<?= /* @noEscape */ $hlabel ?>" name="<?= /* @noEscape */ $id ?>" value="<?= /* @noEscape */ $id ?>"><?= /* @noEscape */ $hlabel ?></option>
                                               <?php
                                               $selected = true;
                                           }
                                       }
                                       if($selected == false){
                                           ?>
                                           <option name="<?= /* @noEscape */ $id ?>" value="<?= /* @noEscape */ $id ?>"><?= /* @noEscape */ $hlabel ?></option>
                                       <?php } } ?>
                               </select>
                           </td>
                       </tr>
                   <?php }
                   }
                   ?>
                   </tbody>
               </table>
           </div>
            <div class="mapping_save_auth">
                <table>
                    <tr>
                        <td>
                            <div class="mapping-actions-btn">
                                <button  id="reset" title="Reset" type="reset"
                                         class="action-default scalable reset primary ui-button ui-corner-all ui-widget">
                                    <span>Reset</span>
                                </button>
                                <button id="save" title="Save" type="button"
                                        class="action-default scalable save primary ui-button ui-corner-all ui-widget">
                                    <span>Save</span>
                                </button>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>
</div>
<script>
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function () {
            $("#reset").click(function () {
                document.location.reload(true);
            });
            $('#save').on('click', () => {
                var data = $('form').serialize();
                $.post('<?= /* @noEscape */ $block->baseUrl() ?>hubintegration/config/mappingsaved', data, function (data){
                    window.location.replace("olddataexportauth");
                });
            });
            var pipeline = $("#selected_pipeline").val();
            var url = '<?= /* @noEscape */ $block->baseUrl() ?>hubintegration/config/selectedpipeline';
            $("#selected_pipeline").on('change', (function() {
                var pipeline = this.value;
                $.post(url,{pipeline:pipeline},function (data){
                    $('#change_pipeline_stage').html(data);
                });
            }));

        });
    })
</script>

