<?php
/**
 * Makewebbetter
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://makewebbetter.com/license-agreement.txt
 *
 * @category    Makewebbetter
 * @package     Makewebbetter_HubIntegration
 * @author      Makewebbetter Core Team <connect@makewebbetter.com>
 * @copyright   Copyright Makewebbetter (http://makewebbetter.com/)
 * @license     https://makewebbetter.com/license-agreement.txt
 */

/** @var  $block \Makewebbetter\HubIntegration\Block\Authorize\Olddataexportauth */
$percentResult = $block->getPercentage();
$contactPercent = $percentResult['CONTACT']['percent'];
$productPercent = $percentResult['PRODUCT']['percent'];
$dealPercent = $percentResult['DEAL']['percent'];
$showProgressBar = $block->showProgressBar();
?>
<div>
    <div class="steps-wrap-message">
        <h3>
            <?php if ($showProgressBar) {?>
                Export Process will be done through cron, to see progress please go to Admin -> HubSpot -> Export page.
            <?php } else { ?>
                Please click on 'EXPORT OLD DATA' button to start Export Process.
            <?php } ?>
        </h3>
    </div>
    <table>
        <tr>
            <?php
            if ($block->getConnectionStatus()) {
                $showExportButton = true;
                $exportButtonLabel = 'Export Old Data';
                if ($block->getBulkExportStartTime()) {
                    if ($block->getBulkExportEndTime()) {
                        $exportButtonLabel = 'Re-Export Old Data';
                    } else {
                        $showExportButton = false;
                    }
                }
                if ($showExportButton) {
            ?>
                <td class="stepswrap-message-actions">
                        <button id="hubspot-export" title="<?= /* @noEscape */ $exportButtonLabel ?>" type="button" class="action-default scalable save primary ui-button ui-corner-all ui-widget">
                            <span><?= /* @noEscape */ $exportButtonLabel ?></span>
                        </button>
            </td>
                    <?php
                }
            }
    ?>
            <td>
                <button id="close" title="Close" type="button" class="action-default scalable save primary ui-button ui-corner-all ui-widget">
                    <span>Close</span>
                </button>
            </td>
        </tr>
    </table>

</div>

<script type="text/x-magento-init">
    {
        "*" :{
            "Makewebbetter_HubIntegration/js/export_auth":{
                "exportUrlWithAbandonedCart" : "<?= /* @noEscape */ $block->getExportUrlWithAbandonedCart(); ?>",
                "exportUrlWithoutAbandonedCart" : "<?= /* @noEscape */ $block->getExportUrlWithoutAbandonedCart(); ?>"
           }
        }
    }
</script>

<script>
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function () {
            $("#close").click(function () {
                closeWindow();
            });
        });
        function closeWindow() {
            setTimeout(function () {
                window.close();
            }, 1000);
        }
    })
</script>
