<?php
/**
 * Makewebbetter
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://makewebbetter.com/license-agreement.txt
 *
 * @category    Makewebbetter
 * @package     Makewebbetter_HubIntegration
 * @author      Makewebbetter Core Team <connect@makewebbetter.com>
 * @copyright   Copyright Makewebbetter (http://makewebbetter.com/)
 * @license     https://makewebbetter.com/license-agreement.txt
 */
?>
<?php
/** @var  $block \Makewebbetter\HubIntegration\Block\Adminhtml\Details\Details\Tabs\Addons */

$status = $block->getConnectionStatus();
$hubSpotVersion = 'V-'.$block->getHubintegrationVersion();

?>
<section class="admin__page-section" id="hub-general-content ">
    <div class="admin__page-section-title hubDashboard_content">
        <span class="title"><?= $block->escapeHtml(__('HubIntegration Extensions and Customisation Services')) ?></span>
        <span class="ver"><?= $block->escapeHtml(__($hubSpotVersion)) ?></span>
    </div>
    <div class="control admin__page-section-content">
        <div class="row admin_hub_dashboard">
            <div class="admin__page-section-item connected">
                <div class="connection-status connected connect-hover">
                    <div class="">
                        <div class="content">
                            <div class="icon"><i class="fa fa-address-book-o"></i></div>
                            <span class="item-description"><?= /* @noEscape */ __('HubGuest User'); ?></span>
                        </div>
                    </div>
                    <div class="bottom-content">
                        <span class="item-title"><b><?= /* @noEscape */ __('Guest Data Syncing'); ?></b></span>
                        <p class="portal_id"><?= /* @noEscape */ __('Synchronize guest data from Magento to HubSpot for enhanced insights, lead capture, and personalized experiences.'); ?></p>
                        <a id="hub_guestuser_cta" title="Hub-Guestuser-CTA" class="action-guest add-on_button" href="https://makewebbetter.com/product/hubspot-magento-guest-user-syncing/?utm_source=backend+&utm_medium=apps&utm_campaign=hubmagento" target="_blank">
                            <span>Get Add-on</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="admin__page-section-item connected">
                <div class="connection-status product product-hover">
                    <div class="">
                        <div class="content">
                            <div class="icon"><i class="fa fa-exchange" style="color: orange;font-size:xxx-large;"></i></div>
                            <span class="item-description"><?= /* @noEscape */ __('HubContact Import'); ?></span>
                        </div>
                    </div>
                    <div class="bottom-content">
                        <span class="item-title"><b><?= /* @noEscape */ __('Two way Syncing'); ?></b></span>
                        <p class="portal_id"><?= /* @noEscape */ __('Enable bi-directional data sync between HubSpot & Magento store, ensuring real-time updates and consistency.'); ?></p>
                        <a id="two_way_syncing_cta" title="Two-Way_syncing-CTA" class="action-twoway-sync add-on_button" href="https://makewebbetter.com/product/hubspot-magento-two-way-syncing/?utm_source=backend+&utm_medium=apps&utm_campaign=hubmagento" target="_blank">
                            <span>Get Add-on</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="admin__page-section-item connected">
                <div class="connection-status connected deal-report deal">
                    <div class="">
                        <div class="content">
                            <div class="icon"><i class="fa fa-random" style="color: blue;"></i></div>
                            <span class="item-description"><?= /* @noEscape */ __('Magento HubSpot Field Mapping'); ?></span>
                        </div>
                    </div>
                    <div class="bottom-content">
                        <span class="item-title"><b><?= /* @noEscape */ __('Magento HubSpot Field Mapping'); ?></b></span>
                        <p class="portal_id"><?= /* @noEscape */ __('Streamline Magento order mapping for HubSpot by defining the fields effortlessly, for improved data accuracy and efficiency.'); ?></p>
                        <a id="field_mapping_cta" title="Field-Mapping-CTA" class="action-field-mapping add-on_button" href="https://makewebbetter.com/product/hubspot-magento-field-mapping/?utm_source=backend+&utm_medium=apps&utm_campaign=hubmagento" target="_blank">
                            <span>Get Add-on</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="admin__page-section-item connected">
                <div class="connection-status connected deal-report report">
                    <div class="">
                        <div class="content">
                            <div class="icon"><i class="fa fa-cogs" style="color: mediumvioletred;"></i></div>
                            <span class="item-description"><?= /* @noEscape */ __('Customisation Services'); ?></span>
                        </div>
                    </div>
                    <div class="bottom-content">
                        <span class="item-title"><b><?= /* @noEscape */ __('Customisation Services'); ?></b></span>
                        <p class="portal_id"><?= /* @noEscape */ __('Tailor our solutions to meet your specific requirements, with expert assistance in adapting and configuring the plugin to align perfectly.'); ?></p>
                        <a id="customisation_services_cta" title="Onboarding-CTA" class="action-customisation add-on_button" href="https://makewebbetter.com/contact-us/?utm_source=backend+&utm_medium=apps&utm_campaign=hubmagento" target="_blank">
                            <span>Get Add-on</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="admin__page-section-title hubDashboard_content">
        <span class="title" style="color:red;"><?= $block->escapeHtml(__('Comprehensive support and guidance for the onboarding process, ensuring a smooth transition and optimal utilization of our solutions.')) ?></span>
        <a id="onboarding_cta" title="Onboarding-CTA" class="action-primary add-on_button" href="https://makewebbetter.com/hubspot-onboarding-services/?utm_source=backend+&utm_medium=apps&utm_campaign=hubmagento" target="_blank">
            <span>Know More</span>
        </a>
    </div>
</section>
