<?php
/**
 * Makewebbetter
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://makewebbetter.com/license-agreement.txt
 *
 * @category    Makewebbetter
 * @package     Makewebbetter_HubIntegration
 * @author      Makewebbetter Core Team <connect@makewebbetter.com>
 * @copyright   Copyright Makewebbetter (http://makewebbetter.com/)
 * @license     https://makewebbetter.com/license-agreement.txt
 */
?>
<?php
/** @var  $block \Makewebbetter\HubIntegration\Block\Adminhtml\Details\Details\Tabs\Contactlists */

$status = $block->getConnectionStatus();
$hubSpotVersion = 'V-'.$block->getHubintegrationVersion();

?>
<section class="admin__page-section detail-content" id=" hub-contactlists-content">
    <div class="admin__page-section-title hubDashboard_content">
        <span class="title"><?= $block->escapeHtml(__('Contact Lists')) ?></span>
        <span class="ver"><?= $block->escapeHtml(__($hubSpotVersion)) ?></span>
    </div>
    <div class="control admin__page-section-content">
        <?php if ($status) { ?>
        <div class="admin__page-section-item-content detail-content custom-table">
            <div class="admin__page-section-item-title">
                <span class="title">List</span>
            </div>
            <table class="admin__table-secondary">
                <?php  $list = $block->createList();
                    foreach ($list as $key => $value) {
                ?>
                <tr><td><?= /* @noEscape */ $value['name'] ?></td></tr>
                <?php } ?>
            </table>
        </div>
            <button type="button" class="view_more action primary">View More</button>
        <?php } else { ?>
            <div class="admin__page-section-item">
                <div class="connection-status disconnected">
                    <div class="graph-circle">
                        <svg viewBox="0 0 36 36" class="circular-chart disconnected">
                            <path class="circle-bg"
                                  d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                            />
                            <path class="circle"
                                  stroke-dasharray="100, 100"
                                  d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                            />
                        </svg>
                        <div class="content">
                            <div class="icon"><i class="fa fa-close"></i></div>
                            <span class="item-description"><?= /* @noEscape */ __('Not Connected'); ?></span>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</section>
<script>
    require([
        'jquery'
    ], function ($) {
        $('.view_more').on('click', () => {

           if ($('.view_more').text() == 'View More') {
               $('.custom-table').addClass('active');
               $('.view_more').text('View Less');
           } else {
               $('.view_more').text('View More');
               $('.custom-table').removeClass('active');
           }
        })
    })
</script>
