<?php
/**
 * Makewebbetter
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://makewebbetter.com/license-agreement.txt
 *
 * @category    Makewebbetter
 * @package     Makewebbetter_HubIntegration
 * @author      Makewebbetter Core Team <connect@makewebbetter.com>
 * @copyright   Copyright Makewebbetter (http://makewebbetter.com/)
 * @license     https://makewebbetter.com/license-agreement.txt
 */
?>
<?php
/** @var  $block \Makewebbetter\HubIntegration\Block\Adminhtml\Details\Details\Tabs\General */

$status = $block->getConnectionStatus();
$hubSpotVersion = 'V-'.$block->getHubintegrationVersion();

?>
<section class="admin__page-section" id="hub-general-content ">
    <div class="admin__page-section-title hubDashboard_content">
        <span class="title"><?= $block->escapeHtml(__('HubSpot Status')) ?></span>
        <span class="ver"><?= $block->escapeHtml(__($hubSpotVersion)) ?></span>
    </div>
    <div class="control admin__page-section-content">
    <?php if ($status) { ?>
        <div class="row admin_hub_dashboard">
            <div class="admin__page-section-item connected">
                <div class="connection-status connected connect-hover">
                    <div class="graph-circle">
                        <svg viewBox="0 0 36 36" class="circular-chart connected">
                            <path class="circle-bg"
                                  d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                            />
                            <path class="circle"
                                  stroke-dasharray="100, 100"
                                  d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                            />
                        </svg>
                        <div class="content">
                            <div class="icon"><i class="fa fa-check"></i></div>
                            <span class="item-description"><?= /* @noEscape */ __('Connected'); ?></span>
                        </div>
                    </div>
                    <div class="bottom-content">
                        <span class="item-title"><b><?= /* @noEscape */ __('HubSpot Portal Id'); ?></b></span>
                        <p class="portal_id"><?= /* @noEscape */ $block->getProtalId(); ?></p>
                    </div>
                </div>
            </div>
            <div class="admin__page-section-item product">
                <div class="connection-status product product-hover">
                    <?php
                    $totalProducts = ($block->getProductStatus('all') == 0) ? 1 : $block->getProductStatus('all');
                    $notSyncedProducts = $block->getProductStatus();
                    $totalSyncedPorducts = (($totalProducts - $notSyncedProducts) * 100)/$totalProducts;
                    ?>
                    <div class="graph-circle">
                        <svg viewBox="0 0 36 36" class="circular-chart product">
                            <path class="circle-bg"
                                  d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                            />
                            <path class="circle"
                                  stroke-dasharray="<?= /* @noEscape */ round($totalSyncedPorducts, 2); ?>, 100"
                                  d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                            />
                        </svg>
                        <div class="content">
                            <?php
                            if ($notSyncedProducts == 0) {
                                echo '<h3>100%</h3><span class="item-description">Synced</span>';
                            } else {
                                ?>
                                <h3><?= /* @noEscape */ floor($totalSyncedPorducts). '%'; ?></h3>
                                <span class="item-description">Synced
                                </span>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="bottom-content">
                        <span class="item-title"><b><?= /* @noEscape */ __('Products Syncing Status'); ?></b></span>
                        <p class="products_synced"><?= /* @noEscape */ __('Total Products - ' . $totalProducts); ?></p>
                        <p class="not_products_synced"><?= /* @noEscape */ __('Not Synced Products - ' . $notSyncedProducts); ?></p>
                    </div>
                </div>
            </div>
            <div class="admin__page-section-item deal-report">
                <div class="connection-status connected deal-report deal">
                    <?php
                    $totalOrder = ($block->getOrderStatus('all') == 0) ? 1 : $block->getOrderStatus('all');
                    $notSyncedOrder = $block->getOrderStatus();
                    $totalSyncedOrder = (($totalOrder - $notSyncedOrder) * 100)/ $totalOrder;
                    ?>

                    <div class="graph-circle">
                        <svg viewBox="0 0 36 36" class="circular-chart deal">
                            <path class="circle-bg"
                                  d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                            />
                            <path class="circle"
                                  stroke-dasharray="<?= /* @noEscape */ round($totalSyncedOrder, 2); ?>, 100"
                                  d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                            />
                        </svg>
                        <div class="content">
                            <?php
                            if ($notSyncedOrder == 0) {
                                echo '<h3>100%</h3><span class="item-description">Synced</span>';
                            } else {
                                ?>
                                <h3><?= /* @noEscape */ floor($totalSyncedOrder). '%'; ?></h3>
                                <span class="item-description">Synced
                                </span>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="bottom-content">
                        <span class="item-title"><b><?= /* @noEscape */ __('Deals Syncing Status'); ?></b></span>
                        <p class="deal_synced"><?= /* @noEscape */ __('Total Deals - ' . $totalOrder); ?></p>
                        <p class="not_deal_synced"><?= /* @noEscape */ __('Not Synced Deals - ' . $notSyncedOrder); ?></p>
                    </div>
                </div>
            </div>
            <div class="admin__page-section-item deal-report">
                <div class="connection-status connected deal-report report">
                    <?php
                    $totalCustomer = ($block->getCustomerStatus('all') == 0) ? 1 : $block->getCustomerStatus('all');;
                    $notSyncedCustomer = $block->getCustomerStatus();
                    $totalSyncedCustomer = (($totalCustomer - $notSyncedCustomer) * 100)/ $totalCustomer;
                    ?>
                    <div class="graph-circle">
                        <svg viewBox="0 0 36 36" class="circular-chart report">
                            <path class="circle-bg"
                                  d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                            />
                            <path class="circle"
                                  stroke-dasharray="<?= /* @noEscape */ round($totalSyncedCustomer, 2); ?>, 100"
                                  d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                            />
                        </svg>
                        <div class="content">
                            <?php
                            if ($notSyncedCustomer == 0) {
                                echo '<h3>100%</h3><span class="item-description">Synced</span>';
                            } else {
                                ?>
                                <h3><?= /* @noEscape */  floor($totalSyncedCustomer). '%'; ?></h3>
                                <span class="item-description">Synced</span>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="bottom-content">
                        <span class="item-title"><b><?= /* @noEscape */ __('Contacts Syncing Status'); ?></b></span>
                        <p class="customer_synced"><?= /* @noEscape */ __('Total Contacts - ' . $totalCustomer); ?></p>
                        <p class="not_customer_synced"><?= /* @noEscape */ __('Not Synced Contacts - ' . $notSyncedCustomer); ?></p>
                    </div>
                </div>
            </div>
        </div>
    <?php } else { ?>
        <div class="admin__page-section-item">
            <div class="connection-status disconnected">
                <div class="graph-circle">
                    <svg viewBox="0 0 36 36" class="circular-chart disconnected">
                        <path class="circle-bg"
                              d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                        />
                        <path class="circle"
                              stroke-dasharray="100, 100"
                              d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                        />
                    </svg>
                    <div class="content">
                        <div class="icon"><i class="fa fa-close"></i></div>
                        <span class="item-description"><?= /* @noEscape */ __('Not Connected'); ?></span>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
    </div>
    <?php
    if($status){
    ?>
    <div class="admin__page-section-title hubDashboard_content">
        <span class="title" style="color:red;font-weight: bold;text-align: center;padding-right: 2%;"><?= $block->escapeHtml(__('Note: This can only be used if you want to connect the store with a new HubSpot Portal. Remember, this will aslo uninstall the integration from your HubSpot portal account and erase all the HubSpot data from the Magento admin pannel.')) ?></span>
        <button id="reset" title="Reset" type="button" class="action-primary reset-hubspot-data" style="min-width: fit-content;">
            <span>Disconnect and Reset HubSpot Data</span>
        </button>
    </div>
    <?php }  ?>
    <script>
        require([
            'jquery',
            'Magento_Ui/js/modal/alert'
        ], function ($, alert) {
            $(document).ready(function () {
                $('#reset').on('click', () => {
                    alert({
                        title: $.mage.__(''),
                        content: $.mage.__('Are you sure to disconnect and reset all data related to HubSpot Portal?'),
                        buttons: [{
                            text: $.mage.__('Cancel'),
                            class: 'action-primary action-accept',
                            click: function () {
                                this.closeModal(true);
                            }
                        },
                        {
                            text: $.mage.__('Disconnect and Reset HubSpot Data'),
                            class: 'action-primary reset-hubspot-data',
                            click: function () {
                                this.closeModal(true);
                                var data = 'reset data';
                                $.post('<?= /* @noEscape */ $block->backendUrl() ?>hubintegration/reset/reset', data, function (data){
                                    location.reload(true);
                                });
                            }
                        }]
                    });
                });
            });
        })
    </script>
</section>
