<?php
/**
 * Makewebbetter
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://makewebbetter.com/license-agreement.txt
 *
 * @category    Makewebbetter
 * @package     Makewebbetter_HubIntegration
 * @author      Makewebbetter Core Team <connect@makewebbetter.com>
 * @copyright   Copyright Makewebbetter (http://makewebbetter.com/)
 * @license     https://makewebbetter.com/license-agreement.txt
 */
?>
<?php
/** @var  $block \Makewebbetter\HubIntegration\Block\Adminhtml\Details\Details\Tabs\Notification */

	$formStatus = $block->getFormStatus();
?>
<section class="admin__page-section" id="hub-notification-content">
	<?php if($block->getConnectionStatus()) { ?>
		<div id="messages">
			<div class="messages hub-notification-content-msg" >
				<p>
					Dear user, HubSpot is discontinuing their eComm Bridge API. But don't worry, it'll have no impact on the integration(s) you're using. We're working on this and will release an update soon with latest APIs to comply with HubSpot's latest norms.<?php if (!$formStatus) { ?> Subscribe to us to stay updated.<?php } ?>
				</p>
			</div>
		</div><?php if (!$formStatus) { ?>
		<div class="control admin__page-section-content">
	        <form id="hs-form-submit" action="<?= /* @noEscape */ $block->gethsFormAction()?>" method="POST">
	            <div class="admin__fieldset-wrapper-content">
	                <fieldset class="admin__fieldset">
	                    <div class="admin__field _required">
	                        <div class="admin__field-label">
	                            <label id="email-label" for="email-input" data-required="true">
	                                <span>Email</span>
	                            </label>
	                        </div>
	                        <div class="admin__field-control">
	                            <input id="email-input" class="admin__control-text" type="email" name="email" required="" autocomplete="email" value="" />
	                        </div>
	                    </div>
	                    <div class="admin__field">
	                        <div class="admin__field-label">
	                            <label id="firstname-label" for="firstname-input" class="admin__control-label" data-required="true">
	                                <span>First Name</span>
	                            </label>
	                        </div>
	                        <div class="admin__field-control">
	                            <input id="firstname-input" class="admin__control-text" type="text" name="firstname" autocomplete="given-name" inputmode="text" aria-invalid="false" aria-labelledby="firstname-label" aria-describedby="firstname-description" aria-required="false" value="">
	                        </div>
	                    </div>
	                    <div class="admin__field">
	                        <div class="admin__field-label">
	                            <label id="lastname-label" for="lastname-input" class="admin__control-label" data-required="true">
	                                <span>Last Name</span>
	                            </label>
	                        </div>
	                        <div class="admin__field-control">
	                            <input id="lastname-input" class="admin__control-text" type="text" name="lastname" autocomplete="family-name" inputmode="text" aria-invalid="false" aria-labelledby="lastname-label" aria-describedby="lastname-description" aria-required="false" value="">
	                        </div>
	                    </div>
	                    <input type="hidden" name="form_key" value="<?= /* @noEscape */ $block->getFormKey() ?>" />

	                    <div class="button-container">
	                        <button id="submit" class="action- scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
	                            <span>Submit</span>
	                        </button>
	                    </div>
	                </fieldset>
	            </div>
	        </form>
	        <div class="admin__field-label">
	            <div class="">
	                <i class="fa fa-wpforms"></i>
	                <i class="fa fa-hubspot"></i>
	                <span> Create your own </span>
	                <a target="_blank" rel="noopener noreferrer" href="">
	                    <span class="fa-brands fa-hubspot">free form with HubSpot</span>
	                </a>
	            </div>
	        </div>
	    </div> <?php } ?>
    <?php } else { ?>
        <div class="admin__page-section-item">
            <div class="connection-status disconnected">
                <div class="graph-circle">
                    <svg viewBox="0 0 36 36" class="circular-chart disconnected">
                        <path class="circle-bg"
                              d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                        />
                        <path class="circle"
                              stroke-dasharray="100, 100"
                              d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                        />
                    </svg>
                    <div class="content">
                        <div class="icon"><i class="fa fa-close"></i></div>
                        <span class="item-description"><?= /* @noEscape */ __('Not Connected'); ?></span>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
</section>
