<?php
/**
 * Makewebbetter
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://makewebbetter.com/license-agreement.txt
 *
 * @category    Makewebbetter
 * @package     Makewebbetter_HubIntegration
 * @author      Makewebbetter Core Team <connect@makewebbetter.com>
 * @copyright   Copyright Makewebbetter (http://makewebbetter.com/)
 * @license     https://makewebbetter.com/license-agreement.txt
 */
?>
<?php
/** @var  $block \Makewebbetter\HubIntegration\Block\Adminhtml\Details\Details\Tabs\Workflow */

$status = $block->getConnectionStatus();
$hubSpotVersion = 'V-'.$block->getHubintegrationVersion();
?>
<section class="admin__page-section hub-workflow-content">
    <div class="admin__page-section-title hubDashboard_content">
        <span class="title"><?= $block->escapeHtml(__('Workflows')) ?></span>
        <span class="ver"><?= $block->escapeHtml(__($hubSpotVersion)) ?></span>
    </div>
    <div class="control admin__page-section-content">
    <?php if ($status) { ?>
        <div id="workflows" class="admin__page-section-item detail-content">
            <?php foreach ($block->getWorkFlowDetails() as $key => $name) { ?>
                <div class="accordion-main">
                    <div class="admin__page-section-item-title accordion-btn" data-role="collapsible" data-role="trigger" >
                        <span class="title"><?= /* @noEscape */  $name; ?></span>
                    </div>
                    <div class="admin__page-section-item-content accordianContent" data-role="content">
                        <table class="admin__table-secondary">
                            <?php $workFlowName = $block->getAllWorkFlows($name);
                            $noWorkflow = 0;
                            foreach ($workFlowName['actions'] as $key2) {
                                if (isset($key2['name'])) { ?>
                                    <tr><td><?= /* @noEscape */ $key2['name'] ?></td></tr>
                                    <?php
                                    $noWorkflow += 1;
                                }
                            }
                            if ($noWorkflow == 0) { ?>
                                <tr><td><?= /* @noEscape */ $name ?></td></tr>
                            <?php  } ?>
                        </table>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } else { ?>
        <div class="admin__page-section-item">
            <div class="connection-status disconnected">
                <div class="graph-circle">
                    <svg viewBox="0 0 36 36" class="circular-chart disconnected">
                        <path class="circle-bg"
                              d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                        />
                        <path class="circle"
                              stroke-dasharray="100, 100"
                              d="M18 2.0845
                              a 15.9155 15.9155 0 0 1 0 31.831
                              a 15.9155 15.9155 0 0 1 0 -31.831"
                        />
                    </svg>
                    <div class="content">
                        <div class="icon"><i class="fa fa-close"></i></div>
                        <span class="item-description"><?= /* @noEscape */ __('Not Connected'); ?></span>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
    </div>
</section>
<script>
    require([
        'jquery',
        'accordion'
    ], function ($) {
        $('#workflows, #group_properties').accordion({
            multipleCollapsible: true,
            collapsible: true,
            animate: {
                duration: 200
            }
        });
    })
</script>
